### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by flatsiedatsie** [holgerl/Slidifier#7]
Hi Guys

I've tried to contact you via the emailaddress provided on the site, but I haven't heard back. One of the things I was curious about is: what licence does this project use?

Totally dig the project! It's so nice and fast to create slides!

**Comment by sheafferusa** [comment]
Hello! 
Any information on the license would really be appreacited by a lot of potential developers including me. 
Please.

Thanks! :)
Waitin'  for your reply!

**Comment by sheafferusa** [comment]
And sir, to add to it, if there's currently no license, Then I would love to recommend one of the best licenses in the Open Source world viz. The MIT license or BSD license. Another one which is awesome is Apache 2.0 used by Google.

**Comment by sheafferusa** [comment]
:( :(

**Comment by holgerl** [comment]
I'll have to admit that I have bee hesitating to decide on what kind of licence there should be. On one hand, I want the project to be easily accessible for all people, on the other hand I don't want people to copy the code andre make their own competing stuff!

**Comment by holgerl** [comment]
The license is now Attribution-NonCommercial-NoDerivs 3.0 Unported: https://creativecommons.org/licenses/by-nc-nd/3.0/

I hope this satisfies the public's needs. If not, let me know!
